### ISSUE TITLE
Compared to react-native-web

### ISSUE THREAD

**Issue by brianyang** [vincentriemer/react-native-dom#25] opened 2018-05-18 11:33 UTC
What are the main differences in this project and react-native-web?

**Comment by remhume** [comment] 2018-05-18 13:16
Duplicate of #17

**Comment by vincentriemer** [comment] 2018-05-20 12:02
Yeah since this is a question a lot of people seem to have I'll see about adding a section to the README on the differences, in the meantime there's already a discussion in #17 so please direct your questions there.

**Closed by vincentriemer** 2018-05-20 12:02 UTC
